### PR TITLE
#83, #87, #97 Update property-view, auto layouting and new model creation

### LINKED ISSUE #83: Use theia and jsonforms property-view implementation instead of prototype
At the moment we use a local built npm package as property-view dependency as the actual dependencies are not merged yet. As soon as this is accomplished, we can get rid of the prototype package.

### LINKED ISSUE #87: Diagram auto layout is not ModelServer aware yet
Triggering the diagram auto layout, does not use model server commands for updating the notation resource yet.
Therefore after auto layouting a diagram, the notation resource is not correctly set and this might lead to inconsistencies.

### LINKED ISSUE #97: [ModelServer] Creating a new diagram no longer works
When opening an *.ecore model without a corresponding *.enotation model, the Diagram (enotation) was automatically created, populated with existing Ecore elements, and auto-layouted. This no longer works on the current model server branch (I'm not sure when it stopped working). Instead, it causes an exception:

```
Error during model loading
org.eclipse.glsp.server.protocol.GLSPServerException: Error during model loading
	at org.eclipse.emfcloud.ecore.glsp.model.EcoreModelServerAccess.getNotationModel(EcoreModelServerAccess.java:116)
	at org.eclipse.emfcloud.ecore.glsp.ResourceManager.createEcoreFacade(ResourceManager.java:87)
	at org.eclipse.emfcloud.ecore.glsp.ResourceManager.<init>(ResourceManager.java:62)
	at org.eclipse.emfcloud.ecore.glsp.EcoreEditorContext.<init>(EcoreEditorContext.java:25)
	at org.eclipse.emfcloud.ecore.glsp.model.EcoreModelFactory.loadModel(EcoreModelFactory.java:70)
	at org.eclipse.glsp.server.actions.RequestModelActionHandler.executeAction(RequestModelActionHandler.java:35)
	at org.eclipse.glsp.server.actions.RequestModelActionHandler.executeAction(RequestModelActionHandler.java:1)
	at org.eclipse.glsp.server.actions.BasicActionHandler.execute(BasicActionHandler.java:45)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.runAction(DefaultActionDispatcher.java:206)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.handleMessage(DefaultActionDispatcher.java:179)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.handleNextMessage(DefaultActionDispatcher.java:164)
	at org.eclipse.glsp.server.internal.action.DefaultActionDispatcher.runThread(DefaultActionDispatcher.java:151)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not parse 'data' field
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.eclipse.emfcloud.ecore.glsp.model.EcoreModelServerAccess.getNotationModel(EcoreModelServerAccess.java:113)
	... 12 more
Caused by: java.lang.RuntimeException: Could not parse 'data' field
	at org.eclipse.emfcloud.modelserver.client.ModelServerClient.lambda$28(ModelServerClient.java:734)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.eclipse.emfcloud.modelserver.client.ModelServerClient.require(ModelServerClient.java:734)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at org.eclipse.emfcloud.modelserver.client.Response.body(Response.java:39)
	at org.eclipse.emfcloud.ecore.glsp.model.EcoreModelServerAccess.lambda$1(EcoreModelServerAccess.java:113)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.eclipse.emfcloud.modelserver.client.ModelServerClient$2.onResponse(ModelServerClient.java:697)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

### PR DESCRIPTION
**Pull request by ndoschek**
- Fixes #83: Update ecore-property-view
  - Update client to GLSP 0.9.0 and Theia 1.12.1
  - Update server to GLSP 0.9.0
  - Remove local jsonforms-property-view dependencies
  - Reuse jsonforms-property-view CSS styling
  - Reuse GLSP selection forwarding

- Fixes #87: Auto layout diagram via Model Server
  - Execute layout operation via Model Server (to ensure operation is able to be undone/redone)
  - Reactivate layout e2e test
  - Add VSCode tasks to run e2e tests

- Fixes #97: Creating a new diagram from existing Ecore model
  - Add client creation of new ecore model (semantic and notation model)
    - Add custom endpoint to create ecore resources
    - Add client command to Theia command palette, file menu and navigator context menu
  - Introduce endpoint to create missing enotation resource for existing semantic resource
    - Adds enotation resource to resourceset and initializes notation diagram from existing semantic resource (epackage)
    - If during model loading the notation resource is unable to load, the creation is triggered
  - Remove DefaultCommandCodec and reuse default ModelServer CommandContributions to encode commands in ModelServerAccess
  - Remove complex update mechanism in SubscriptionListener and reload models
  - Reactivate auto layout test and adjust create/delete ecore test
  - Update sample models in client/workspace
  - Move Enotation model and its generated code to org.eclipse.emfcloud.ecore.modelserver to avoid circular dependency

### CODE REVIEW

**Comment by CamilleLetavernier** [comment]
When I delete "empty.enotation" and then open "empty.ecore", the Model Server throws some exceptions (Which in turn results in an Internal Server Error, causing a json-parse error on the GLSP Side):

```
3364 [qtp501261420-43] INFO ProviderDefaults  - GET /api/v1/models?modeluri=empty%2Fmodel%2Fempty.ecore&format=xmi -> Status: 200 (took 4.006247 ms)
3382 [qtp501261420-43] INFO ProviderDefaults  - GET /api/v1/models?modeluri=empty%2Fmodel%2Fempty.enotation&format=xmi -> Status: 200 (took 2.500375 ms)
11:10:00.994 [qtp501261420-39] WARN io.javalin.Javalin - Uncaught exception
java.lang.IllegalArgumentException: No value present (through reference chain: java.util.Collections$UnmodifiableRandomAccessList[5]->java.util.Collections$UnmodifiableRandomAccessList[0])
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2978)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelValidator.validate(DefaultModelValidator.java:63)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultSessionController.broadcastValidation(DefaultSessionController.java:162)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultSessionController.commandExecuted(DefaultSessionController.java:136)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.executeCommand(DefaultModelController.java:279)
	at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.lambda$37(ModelServerRoutingV1.java:206)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:201)
	at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.executeCommand(ModelServerRoutingV1.java:205)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
	at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
	at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No value present (through reference chain: java.util.Collections$UnmodifiableRandomAccessList[5]->java.util.Collections$UnmodifiableRandomAccessList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:368)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:338)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:123)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2804)
	at com.fasterxml.jackson.databind.util.TokenBuffer.writeObject(TokenBuffer.java:936)
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1769)
	at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:79)
	at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:1)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2804)
	at com.fasterxml.jackson.databind.util.TokenBuffer.writeObject(TokenBuffer.java:936)
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1769)
	at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:79)
	at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:1)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2804)
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2973)
	... 47 common frames omitted
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:72)
	at org.eclipse.emfcloud.modelserver.emf.common.ValidationMapperModule$BasicDiagnosticSerializer.serialize(ValidationMapperModule.java:1)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	... 70 common frames omitted
3418 [qtp501261420-39] INFO ProviderDefaults  - PATCH /api/v1/edit?modeluri=empty%2Fmodel%2Fempty.ecore&format=xmi -> Status: 500 (took 112.482834 ms)
4535 [qtp501261420-44] INFO ProviderDefaults  - GET /api/v1/modelelement?modeluri=/home/camille/Git/ecore-glsp/client/workspace/empty/model/empty.ecore&elementid=/&format=[object%20Object] -> Status: 200 (took 7.468557 ms)
4578 [qtp501261420-45] INFO ProviderDefaults  - GET /api/v1/uischema?schemaname=epackage -> Status: 200 (took 1.809905 ms)
```

As far as I can tell, this doesn't seem to affect the behavior of the diagram (It's properly open and we can edit the diagram), but a similar exception is thrown on each edit operation. When I do the same steps for the UML Model however, I don't see this exception.

**Comment by CamilleLetavernier** [comment]
I also get a different error when I create a new Ecore model (Via Right Click => New Ecore Model Diagram):

```
576061 [qtp501261420-44] INFO ProviderDefaults  - GET /api/v1/ecore/create?modeluri=test3/model/test3.ecore&nsUri=ns3&nsPrefix=uri3 -> Status: 200 (took 3.479299 ms)
579111 [qtp501261420-40] INFO ProviderDefaults  - WS Connected: 0e45c163-3e9e-4d5f-b5b1-77796cec5e83
579116 [qtp501261420-38] INFO ProviderDefaults  - GET /api/v1/models?modeluri=test3%2Fmodel%2Ftest3.ecore&format=xmi -> Status: 200 (took 0.901243 ms)
579122 [qtp501261420-40] INFO ProviderDefaults  - GET /api/v1/models?modeluri=test3%2Fmodel%2Ftest3.enotation&format=xmi -> Status: 200 (took 0.974412 ms)
579238 [qtp501261420-52] INFO ProviderDefaults  - WS Closed: 357036a6-2d5b-4139-aa52-3827042bb86a
579241 [qtp501261420-41] INFO ProviderDefaults  - WS Connected: 74288c2a-9788-4eda-a10a-7ec5315718c1
579241 [qtp501261420-44] INFO ProviderDefaults  - GET /api/v1/modelelement?modeluri=/home/camille/Git/ecore-glsp/client/workspace/test3/model/test3.ecore&elementid=/&format=[object%20Object] -> Status: 200 (took 0.689727 ms)
579254 [qtp501261420-40] INFO ProviderDefaults  - GET /api/v1/uischema?schemaname=epackage -> Status: 200 (took 0.910021 ms)
11:19:37.152 [qtp501261420-38] WARN io.javalin.Javalin - Uncaught exception
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.xml.sax.SAXParseExceptionpublicId: http://www.eclipsesource.com/schema/2019/modelserver/command; systemId: http://www.eclipsesource.com/schema/2019/modelserver/command; lineNumber: 1; columnNumber: 1; Premature end of file.
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:406)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:220)
	at org.emfjson.jackson.databind.EMFContext.findEClass(EMFContext.java:145)
	at org.emfjson.jackson.annotations.EcoreTypeInfo.lambda$static$0(EcoreTypeInfo.java:33)
	at org.emfjson.jackson.databind.property.EObjectTypeProperty.create(EObjectTypeProperty.java:74)
	at org.emfjson.jackson.databind.property.EObjectTypeProperty.deserialize(EObjectTypeProperty.java:70)
	at org.emfjson.jackson.databind.deser.EObjectDeserializer.deserialize(EObjectDeserializer.java:73)
	at org.emfjson.jackson.databind.deser.EObjectDeserializer.deserialize(EObjectDeserializer.java:38)
	at org.emfjson.jackson.databind.deser.ResourceDeserializer.deserialize(ResourceDeserializer.java:75)
	at org.emfjson.jackson.databind.deser.ResourceDeserializer.deserialize(ResourceDeserializer.java:30)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1721)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1228)
	at org.emfjson.jackson.resource.JsonResource.doLoad(JsonResource.java:191)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.emfcloud.modelserver.common.codecs.DefaultJsonCodec.decode(DefaultJsonCodec.java:60)
	at org.eclipse.emfcloud.modelserver.emf.common.codecs.DICodecsManager.decode(DICodecsManager.java:101)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.readPayload(DefaultModelController.java:259)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.executeCommand(DefaultModelController.java:273)
	at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.lambda$37(ModelServerRoutingV1.java:206)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:201)
	at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.executeCommand(ModelServerRoutingV1.java:205)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
	at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
	at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
	at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.xml.sax.SAXParseException: Premature end of file.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1013)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 61 common frames omitted
```

File: client/packages/theia-ecore/src/browser/command-contribution.ts [hunk 1]
```diff
@@ -187,6 +148,56 @@ export class EcoreCommandContribution implements CommandContribution {
...
+            }
+        };
+        this.quickOpenService.open(quickOpenModel, this.getOptions(hint, false));
+    }
+
+    protected createEcoreModelDiagram(modelName: string, workspaceUri: URI, nsUri: string, nsPrefix: string): void {
+        if (modelName) {
+            this.modelServerClient.createEcoreResources(modelName, nsUri, nsPrefix).then(() => {
+                this.quickOpenService.hide();
+                const modelUri = new URI(workspaceUri.path.toString() + `/${modelName}/model/${modelName}.uml`);
```
Comment (CamilleLetavernier) [inline client/packages/theia-ecore/src/browser/command-contribution.ts:191]: .uml? :)

Comment (ndoschek) [reply client/packages/theia-ecore/src/browser/command-contribution.ts:191]: Good catch, thanks! :)

**Comment by ndoschek** [comment]
Thank you for your comments so far Camille!
This are good catches, currently the modelserver does not get notified if files (resources) are deleted from the Theia editor. During implementation I simply reloaded everytime after deleting a file, so I was not aware of this issue. But I will add a file watcher to properly handle removing resources and notify the model server about that!

File: client/packages/theia-ecore/src/browser/workspace-delete-handler.ts [hunk 2]
```diff
@@ -0,0 +1,190 @@
...
+            } else {
+                if (await this.isEcoreDirectory(resourceUri)) {
+                    const ecoreResourceUri = await this.getContainedEcoreFileUri(resourceUri);
+                    const enotationUri = this.getEnotationFileUri(ecoreResourceUri!);
+                    await Promise.all([
+                        this.closeEcoreDiagramWidget(this.shell, ecoreResourceUri!),
+                        this.closeWithoutSaving(enotationUri),
+                        this.fileService.delete(resourceUri, options)
+                    ]);
+                    await this.modelServerClient.deleteEcoreResources(ecoreResourceUri!.toString());
```
Comment (CamilleLetavernier) [inline client/packages/theia-ecore/src/browser/workspace-delete-handler.ts:128]: As mentioned in eclipse-emfcloud/emfcloud-modelserver-theia/issues/50, I'm not convinced that Theia should have to notify the Model Server about file system resource changes; the Model Server itself should check the resources. However, since both Theia and the Model Server may have independent access to the same file system, this is a more complex synchronization issue; so we can think about better solutions later on.

**Review by CamilleLetavernier — COMMENTED** [review]
In general, the changes look good to me. However, it seems that the Properties/TreeEditor is broken for me, as any change occurring in either views will cause an exception on the ModelServer. For example, when trying to check "Abstract" for a Class:

```
10:09:34.227 [qtp1135870515-54] WARN io.javalin.Javalin - Uncaught exception
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.xml.sax.SAXParseExceptionpublicId: http://www.eclipsesource.com/schema/2019/modelserver/command; systemId: http://www.eclipsesource.com/schema/2019/modelserver/command; lineNumber: 1; columnNumber: 1; Premature end of file.
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:406)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:220)
	at org.emfjson.jackson.databind.EMFContext.findEClass(EMFContext.java:145)
	at org.emfjson.jackson.annotations.EcoreTypeInfo.lambda$static$0(EcoreTypeInfo.java:33)
	at org.emfjson.jackson.databind.property.EObjectTypeProperty.create(EObjectTypeProperty.java:74)
	at org.emfjson.jackson.databind.property.EObjectTypeProperty.deserialize(EObjectTypeProperty.java:70)
	at org.emfjson.jackson.databind.deser.EObjectDeserializer.deserialize(EObjectDeserializer.java:73)
	at org.emfjson.jackson.databind.deser.EObjectDeserializer.deserialize(EObjectDeserializer.java:38)
	at org.emfjson.jackson.databind.deser.ResourceDeserializer.deserialize(ResourceDeserializer.java:75)
	at org.emfjson.jackson.databind.deser.ResourceDeserializer.deserialize(ResourceDeserializer.java:30)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1721)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1228)
	at org.emfjson.jackson.resource.JsonResource.doLoad(JsonResource.java:191)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.emfcloud.modelserver.common.codecs.DefaultJsonCodec.decode(DefaultJsonCodec.java:60)
	at org.eclipse.emfcloud.modelserver.emf.common.codecs.DICodecsManager.decode(DICodecsManager.java:101)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.readPayload(DefaultModelController.java:259)
	at org.eclipse.emfcloud.modelserver.emf.common.DefaultModelController.executeCommand(DefaultModelController.java:273)
	at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.lambda$37(ModelServerRoutingV1.java:206)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:201)
	at org.eclipse.emfcloud.modelserver.emf.common.ModelServerRoutingV1.executeCommand(ModelServerRoutingV1.java:205)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
	at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
[....]
1465040 [qtp1135870515-54] INFO ProviderDefaults  - PATCH /api/v1/edit?modeluri=UML/model/UML.ecore -> Status: 500 (took 113.50482 ms)
```

File: client/packages/theia-ecore/src/browser/workspace-delete-handler.ts (hunk 2 above)
Comment (ndoschek) [reply client/packages/theia-ecore/src/browser/workspace-delete-handler.ts:128]: Thanks for pointing that out, I agree! We also moved the mentioned issue directly to the modelserver component: https://github.com/eclipse-emfcloud/emfcloud-modelserver/issues/115

**Comment by ndoschek** [comment]
Thanks for your review Camille! Regarding the updating issue, that could be solved by updating both JsonForms based components to the latest versions. This includes also an update to the latest `modelserver-theia` version, which allows to send updates with the latest and correct command format to the model server.

File: client/browser-app/package.json [hunk 3]
```diff
@@ -3,33 +3,41 @@
...
-    "@theia/messages": "^1.12.1",
-    "@theia/monaco": "^1.12.1",
-    "@theia/navigator": "^1.12.1",
-    "@theia/plugin-ext-vscode": "^1.12.1",
-    "@theia/preferences": "^1.12.1",
-    "@theia/process": "^1.12.1",
-    "@theia/property-view": "^1.12.1",
-    "@theia/terminal": "^1.12.1",
-    "@theia/workspace": "^1.12.1"
+    "@theia/core": "^1.0.0",
```
Comment (CamilleLetavernier) [inline client/browser-app/package.json:10]: I don't know about the ModelServer and TreeEditor, but I'm pretty sure GLSP doesn't support any older version of Theia. Is there a specific reason to relax the Theia dependency versions? (It doesn't really matter, since GLSP will add more constraints anyway; but I'm curious about the change)

**Review by CamilleLetavernier — APPROVED** [review]
The changes look good to me, it works great. Thanks!

File: client/browser-app/package.json (hunk 3 above)
Comment (ndoschek) [reply client/browser-app/package.json:10]: I aligned it with both `eclipse-glsp` and `eclipse-emfcloud` projects where we use the relaxed version of Theia instead of a locked one (e.g. https://github.com/eclipse-glsp/glsp-theia-integration/blob/master/examples/browser-app/package.json).
